Lightning automatically upgraded your loaded checkpoint from v1.6.5 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../baopengfei/gitsoft/exosomians/saved_models/ExoGRU/exogru_best-v2.ckpt`
Model successfully restored!
Successfully loaded the dataset with 129 sequences!
  0%|          | 0/2 [00:00<?, ?it/s] 50%|█████     | 1/2 [07:11<07:11, 431.68s/it]100%|██████████| 2/2 [07:18<00:00, 181.93s/it]100%|██████████| 2/2 [07:18<00:00, 219.39s/it]
Results saved to ./output.csv
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f437c4e1740 (most recent call first):
exoGRU_pred.sh: line 1: 33021 Aborted                 python /BioII/lulab_b/huangkeyun/zhangys/RNA_locator/repeated_works/exosomians/pred_EV_fasta.py /BioII/lulab_b/huangkeyun/zhangys/RNA_locator/python_scripts/ML_models/circRNA_ML_Model_Output/test_set_sequences.fasta ./output1.csv
Traceback (most recent call last):
  File "/BioII/lulab_b/huangkeyun/zhangys/RNA_locator/repeated_works/exosomians/pred_EV_fasta.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Lightning automatically upgraded your loaded checkpoint from v1.6.5 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../baopengfei/gitsoft/exosomians/saved_models/ExoGRU/exogru_best-v2.ckpt`
Model successfully restored!
Traceback (most recent call last):
  File "/BioII/lulab_b/huangkeyun/zhangys/RNA_locator/repeated_works/exosomians/pred_EV_fasta.py", line 32, in <module>
    main(fasta_file_path, output_file_path)
  File "/BioII/lulab_b/huangkeyun/zhangys/RNA_locator/repeated_works/exosomians/pred_EV_fasta.py", line 16, in main
    data = model.prepare_data(fasta_file_path, seq_key='seq')
  File "/BioII/lulab_b/huangkeyun/zhangys/RNA_locator/repeated_works/exosomians/exopy/models/_model.py", line 72, in prepare_data
    path_or_df = load_fasta(path_or_df, seq_key, target_key)
  File "/BioII/lulab_b/huangkeyun/zhangys/RNA_locator/repeated_works/exosomians/exopy/utils.py", line 11, in load_fasta
    with open(path) as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/BioII/lulab_b/huangkeyun/zhangys/RNA_locator/python_scripts/ML_models/circRNA_ML_Model_Output/test_set_sequences.fasta'
Lightning automatically upgraded your loaded checkpoint from v1.6.5 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../../baopengfei/gitsoft/exosomians/saved_models/ExoGRU/exogru_best-v2.ckpt`
Model successfully restored!
Successfully loaded the dataset with 129 sequences!
  0%|          | 0/2 [00:00<?, ?it/s] 50%|█████     | 1/2 [00:05<00:05,  5.03s/it]100%|██████████| 2/2 [00:05<00:00,  2.13s/it]100%|██████████| 2/2 [00:05<00:00,  2.56s/it]
Results saved to ./output1.csv
